### ISSUE TITLE
Missing synthWaveStyles.css

### ISSUE THREAD

**Issue by joeyessak** [TanvirUthsho/source-theme-vscode#1]
Unable to locate this file  "synthWaveStyles.css"   in the repository or the extension bundle upon installation. I am following the instructions To enable the gradients in active tabs so I checked for this directory locally on my machine and this file is missing and I don't see it as well any where on the repository could you please provide me this file so I may activate this feature 
    "file:///C:/Users/{your username}/.vscode/extensions/thuthsho.source-theme-11.3.0/synthWaveStyles.css"

**Comment by TanvirUthsho** [comment]
I have solved the issue you mentioned. Thank you for using Source Theme in
VSCode.

**Comment by joeyessak** [comment]
Thank you for updating the bundle previous issue has been resolved and no longer present gradient on active tabs is now working everything looks great and  works as expected.
